classmates = ['Michael', 'Bob', 'Tracy']
print (classmates)
classmates_length = len(classmates)
print (classmates_length)
print (classmates[2])
print (classmates[-2])
print (classmates[-3])
classmates.insert(1, 'jack')
classmates.append('Adam')
print (classmates)